name: Run tests (Win)

# Manual start only. Trying the save some minutes :) 
on:  
  workflow_dispatch:
  push: # TMP (remove this)

# Cancel in-progress jobs/runs for the same workflow; if you push to same
# pull request twice, the previous workflow should be canceled.
# From: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: win-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:  
  test-windows-py310:
    # Windows Server 2022
    # See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python 
        uses: actions/setup-python@v4 
        with:
          python-version: '3.10' 
      - name: Show OS version
        run: systeminfo
      - name: Show environment variables
        run: "Get-ChildItem Env: | Format-Table -Wrap -AutoSize"
      - name: Show python version
        run: python --version
      - name: Show platform information
        run: python -c "import platform; print(platform.platform())"
      - name: install tox
        run: |
          python -m pip install -U pip wheel &&`
          python -m pip install tox~=4.6.0
      - name: Run tests with tox
        run: tox -e win-py310
